# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = true

# Replace the symbol in the prompt
[character]
success_symbol = "[](green)"
vicmd_symbol = "[](green)"
error_symbol = "[✗](red)"

[nodejs]
disabled = true

[java]
disabled = true

[golang]
disabled = true

[python]
disabled = true

[perl]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true
