require("rc.settings")
require("rc.keymaps")
require("rc.plugins")
require("rc.treesitter")
require("rc.colorscheme")
require("rc.lualine")
require("rc.nvim-tree")
require("rc.telescope")
require("rc.autopairs")
require("rc.toggleterm")
require("rc.colorizer")
require("rc.indent-blankline")
require("rc.gitsigns")
require("rc.which-key")
require("rc.lastplace")
require("rc.alpha")

-- LSP
require("rc.lsp.mason")
require("rc.lsp.cmp")
require("rc.lsp.diagnostic")
require("rc.lsp.lsp-colors")
